In [2]:
import pandas as pd
import numpy as np
from datetime import datetime as dt

In [4]:
#Import Sports Data
sportURL="https://raw.githubusercontent.com/holden-herrell/IST718_GROUP_PROJECT/master/DATASETS/COMBINED%20DATA/Sports.csv"
Sports=pd.DataFrame(pd.read_csv(sportURL, engine='python', error_bad_lines=False))

In [5]:
#Import Accident Data
atlURL="https://raw.githubusercontent.com/holden-herrell/IST718_GROUP_PROJECT/master/DATASETS/ACCIDENT%20DATA/ATL_Accidents.csv"
dalURL="https://raw.githubusercontent.com/holden-herrell/IST718_GROUP_PROJECT/master/DATASETS/ACCIDENT%20DATA/DAL_Accidents.csv"
houURL="https://raw.githubusercontent.com/holden-herrell/IST718_GROUP_PROJECT/master/DATASETS/ACCIDENT%20DATA/HOU_Accidents.csv"
miaURL="https://raw.githubusercontent.com/holden-herrell/IST718_GROUP_PROJECT/master/DATASETS/ACCIDENT%20DATA/MIA_Accidents.csv"
ATLraw=pd.read_csv(atlURL, engine='python', error_bad_lines=False)
ATL=pd.DataFrame(ATLraw)
DALraw=pd.read_csv(dalURL, engine='python', error_bad_lines=False)
DAL=pd.DataFrame(DALraw)
HOUraw=pd.read_csv(houURL, engine='python', error_bad_lines=False)
HOU=pd.DataFrame(HOUraw)
MIAraw=pd.read_csv(miaURL, engine='python', error_bad_lines=False)
MIA=pd.DataFrame(MIAraw)

In [6]:
display(MIA)

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Number,Side,...,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset
0,2,2017-01-02 13:40:24,2017-01-02 15:10:02,25.643578,-80.334251,NaN,NaN,0.010,13627.0,R,...,False,False,False,False,True,False,False,True,False,Day
1,2,2017-01-02 14:38:32,2017-01-02 15:07:59,25.928244,-80.196335,NaN,NaN,0.010,NaN,R,...,False,False,False,False,True,False,False,True,False,Day
2,2,2017-01-02 16:40:30,2017-01-02 17:09:22,25.760900,-80.392502,NaN,NaN,0.010,12198.0,R,...,False,False,False,False,False,False,False,True,False,Day
3,2,2017-01-02 17:08:53,2017-01-02 17:38:32,25.847086,-80.208138,NaN,NaN,0.010,NaN,R,...,False,False,False,False,False,False,False,True,False,Day
4,2,2017-01-02 17:17:21,2017-01-02 17:47:04,25.963621,-80.146988,NaN,NaN,0.010,NaN,R,...,False,False,False,False,False,False,False,True,False,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37910,4,2019-08-23 02:01:46,2019-08-23 02:30:39,25.927371,-80.212694,25.927371,-80.212694,0.000,16646.0,L,...,False,False,False,False,False,False,False,False,False,Night
37911,2,2019-08-23 07:23:31,2019-08-23 07:52:12,25.971230,-80.288240,25.970860,-80.301050,0.796,NaN,R,...,False,False,False,False,False,False,False,False,False,Day
37912,2,2019-08-23 13:08:31,2019-08-23 13:37:40,25.812250,-80.237460,25.812460,-80.243590,0.382,NaN,R,...,True,False,False,False,False,False,False,False,False,Day
37913,3,2019-08-23 12:52:20,2019-08-23 13:21:35,26.127890,-80.169540,26.116920,-80.169060,0.759,NaN,R,...,True,False,False,False,False,False,False,False,False,Day
37914,4,2019-08-23 19:14:05,2019-08-23 19:43:39,25.935950,-80.199180,25.932061,-80.203819,0.394,NaN,R,...,False,False,False,False,False,False,False,False,False,Day

In [7]:
#Remove Unneeded Accident columns
#ATL=ATL.drop(columns=['ID','Description','County','Country','Airport_Code','TMC','Source','Street','Timezone'])
#DAL=DAL.drop(columns=['ID','Description','County','Country','Airport_Code','TMC','Source','Street','Timezone'])
#HOU=HOU.drop(columns=['ID','Description','County','Country','Airport_Code','TMC','Source','Street','Timezone'])
#MIA=MIA.drop(columns=['ID','Description','County','Country','Airport_Code','TMC','Source','Street','Timezone'])

In [8]:
#Add Date Field
ATL['Date']=pd.to_datetime(ATL['Start_Time'], format= '%Y-%m-%d').dt.date
DAL['Date']=pd.to_datetime(DAL['Start_Time'], format= '%Y-%m-%d').dt.date
HOU['Date']=pd.to_datetime(HOU['Start_Time'], format= '%Y-%m-%d').dt.date
MIA['Date']=pd.to_datetime(MIA['Start_Time'], format= '%Y-%m-%d').dt.date

In [9]:
#Calculate accident clean up time
ATL['CleanUpTime']=pd.to_datetime(ATL['End_Time'])-pd.to_datetime(ATL['Start_Time'])
DAL['CleanUpTime']=pd.to_datetime(DAL['End_Time'])-pd.to_datetime(DAL['Start_Time'])
HOU['CleanUpTime']=pd.to_datetime(HOU['End_Time'])-pd.to_datetime(HOU['Start_Time'])
MIA['CleanUpTime']=pd.to_datetime(MIA['End_Time'])-pd.to_datetime(MIA['Start_Time'])

In [10]:
#Remove Extra Time columns
ATL=ATL.drop(columns=['Start_Time','End_Time','Weather_Timestamp'])
DAL=DAL.drop(columns=['Start_Time','End_Time','Weather_Timestamp'])
HOU=HOU.drop(columns=['Start_Time','End_Time','Weather_Timestamp'])
MIA=MIA.drop(columns=['Start_Time','End_Time','Weather_Timestamp'])

In [11]:
display(MIA)

,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Number,Side,City,State,...,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Date,CleanUpTime
0,2,25.643578,-80.334251,NaN,NaN,0.010,13627.0,R,Miami,FL,...,False,False,True,False,False,True,False,Day,2017-01-02,01:29:38
1,2,25.928244,-80.196335,NaN,NaN,0.010,NaN,R,Miami,FL,...,False,False,True,False,False,True,False,Day,2017-01-02,00:29:27
2,2,25.760900,-80.392502,NaN,NaN,0.010,12198.0,R,Miami,FL,...,False,False,False,False,False,True,False,Day,2017-01-02,00:28:52
3,2,25.847086,-80.208138,NaN,NaN,0.010,NaN,R,Miami,FL,...,False,False,False,False,False,True,False,Day,2017-01-02,00:29:39
4,2,25.963621,-80.146988,NaN,NaN,0.010,NaN,R,Miami,FL,...,False,False,False,False,False,True,False,Day,2017-01-02,00:29:43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37910,4,25.927371,-80.212694,25.927371,-80.212694,0.000,16646.0,L,Miami,FL,...,False,False,False,False,False,False,False,Night,2019-08-23,00:28:53
37911,2,25.971230,-80.288240,25.970860,-80.301050,0.796,NaN,R,Miami,FL,...,False,False,False,False,False,False,False,Day,2019-08-23,00:28:41
37912,2,25.812250,-80.237460,25.812460,-80.243590,0.382,NaN,R,Miami,FL,...,False,False,False,False,False,False,False,Day,2019-08-23,00:29:09
37913,3,26.127890,-80.169540,26.116920,-80.169060,0.759,NaN,R,Miami,FL,...,False,False,False,False,False,False,False,Day,2019-08-23,00:29:15
37914,4,25.935950,-80.199180,25.932061,-80.203819,0.394,NaN,R,Miami,FL,...,False,False,False,False,False,False,False,Day,2019-08-23,00:29:34

In [12]:
#Join all accident data sets
ATL['JoinID']=ATL['Date'].astype(str)+ATL['City'].astype(str)+ATL['State'].astype(str)
DAL['JoinID']=DAL['Date'].astype(str)+DAL['City'].astype(str)+DAL['State'].astype(str)
HOU['JoinID']=HOU['Date'].astype(str)+HOU['City'].astype(str)+HOU['State'].astype(str)
MIA['JoinID']=MIA['Date'].astype(str)+MIA['City'].astype(str)+MIA['State'].astype(str)
US=pd.DataFrame(pd.concat([ATL,DAL,HOU,MIA], axis=0, join='outer', ignore_index=False, keys='JoinID',
          levels=None, names=None, verify_integrity=False, copy=True, sort=True))

In [13]:
display(US)

        Airport_Code  Amenity Astronomical_Twilight   Bump     City  \
J 0              NaN    False                   NaN  False  Atlanta
  1              NaN    False                   NaN  False  Atlanta
  2              NaN    False                   NaN  False  Atlanta
  3              NaN    False                   NaN  False  Atlanta
  4              NaN    False                   NaN  False  Atlanta
...              ...      ...                   ...    ...      ...
n 37910          NaN    False                   NaN  False    Miami
  37911          NaN    False                   NaN  False    Miami
  37912          NaN    False                   NaN  False    Miami
  37913          NaN    False                   NaN  False    Miami
  37914          NaN    False                   NaN  False    Miami

        Civil_Twilight CleanUpTime Country County  Crossing  ... Timezone  \
J 0                NaN    01:15:27     NaN    NaN     False  ...      NaN
  1                NaN    01:15:34     NaN    NaN     False  ...      NaN
  2                NaN    00:59:34     NaN    NaN     False  ...      NaN
  3                NaN    00:29:40     NaN    NaN     False  ...      NaN
  4                NaN    00:29:20     NaN    NaN     False  ...      NaN
...                ...         ...     ...    ...       ...  ...      ...
n 37910            NaN    00:28:53     NaN    NaN     False  ...      NaN
  37911            NaN    00:28:41     NaN    NaN     False  ...      NaN
  37912            NaN    00:29:09     NaN    NaN     False  ...      NaN
  37913            NaN    00:29:15     NaN    NaN     False  ...      NaN
  37914            NaN    00:29:34     NaN    NaN     False  ...      NaN

        Traffic_Calming  Traffic_Signal  Turning_Loop  Visibility(mi)  \
J 0               False           False         False             0.2
  1               False           False         False             0.2
  2               False           False         False             0.5
  3               False           False         False             1.0
  4               False           False         False             1.0
...                 ...             ...           ...             ...
n 37910           False           False         False            10.0
  37911           False           False         False            10.0
  37912           False           False         False            10.0
  37913           False           False         False            10.0
  37914           False           False         False            10.0

         Weather_Condition  Wind_Chill(F) Wind_Direction Wind_Speed(mph)  \
J 0             Light Rain            NaN            NNE             8.1
  1             Light Rain            NaN            NNE             8.1
  2             Light Rain            NaN             NE             6.9
  3             Light Rain            NaN       Variable             4.6
  4             Light Rain            NaN       Variable             4.6
...                    ...            ...            ...             ...
n 37910               Fair           81.0             NE             7.0
  37911               Fair           80.0            NNW             5.0
  37912             Cloudy           87.0              N             7.0
  37913      Partly Cloudy           85.0            ENE            12.0
  37914               Fair           85.0             NE             8.0

            Zipcode
J 0           30354
  1           30312
  2           30093
  3           30324
  4           30342
...             ...
n 37910  33169-5811
  37911       33025
  37912       33142
  37913       33311
  37914       33162

[200099 rows x 49 columns]

In [14]:
#Merge all datsets
USAgg=pd.merge(US,Sports, how='outer', on=['JoinID', 'JoinID'])

In [15]:
display(USAgg)

,Airport_Code,Amenity,Astronomical_Twilight,Bump,City_x,Civil_Twilight,CleanUpTime,Country,County,Crossing,...,City_y,Date_y,Day of Week,MLBGame,MLB_Attendance,NBAGame,NBA_Attendance,NFLGame,NFL_Attendance,State_y
0,NaN,False,NaN,False,Atlanta,NaN,01:15:27,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,False,NaN,False,Atlanta,NaN,01:15:34,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,False,NaN,False,Atlanta,NaN,00:59:34,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,False,NaN,False,Atlanta,NaN,00:29:40,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,False,NaN,False,Atlanta,NaN,00:29:20,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207194,NaN,False,NaN,False,Miami,NaN,06:00:00,NaN,NaN,False,...,Miami,2017-07-31,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,FL
207195,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,Houston,2018-07-15,Sunday,1.0,39455.0,0.0,0.0,0.0,0.0,TX
207196,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,Houston,2019-08-24,Saturday,1.0,37862.0,0.0,0.0,0.0,0.0,TX
207197,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,Miami,2019-08-24,Saturday,1.0,12981.0,0.0,0.0,0.0,0.0,FL
207198,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,Atlanta,2017-01-01,Sunday,0.0,0.0,1.0,18088.0,0.0,0.0,GA

In [16]:
#Rename Columns, drop extras from join
USAgg.rename(columns={'City_x':'City','Date_x':'Date','State_x':'State'},inplace=True)
USAgg=USAgg.drop(columns=['City_y','Date_y','State_y', 'JoinID'])

In [17]:
#Fill NA values for sports
USAgg['MLBGame'].fillna(0, inplace=True)
USAgg['NBAGame'].fillna(0, inplace=True)
USAgg['NFLGame'].fillna(0, inplace=True)
USAgg['MLB_Attendance'].fillna(0, inplace=True)
USAgg['NBA_Attendance'].fillna(0, inplace=True)
USAgg['NFL_Attendance'].fillna(0, inplace=True)

In [18]:
display(USAgg)

,Airport_Code,Amenity,Astronomical_Twilight,Bump,City,Civil_Twilight,CleanUpTime,Country,County,Crossing,...,Wind_Direction,Wind_Speed(mph),Zipcode,Day of Week,MLBGame,MLB_Attendance,NBAGame,NBA_Attendance,NFLGame,NFL_Attendance
0,NaN,False,NaN,False,Atlanta,NaN,01:15:27,NaN,NaN,False,...,NNE,8.1,30354,NaN,0.0,0.0,0.0,0.0,0.0,0.0
1,NaN,False,NaN,False,Atlanta,NaN,01:15:34,NaN,NaN,False,...,NNE,8.1,30312,NaN,0.0,0.0,0.0,0.0,0.0,0.0
2,NaN,False,NaN,False,Atlanta,NaN,00:59:34,NaN,NaN,False,...,NE,6.9,30093,NaN,0.0,0.0,0.0,0.0,0.0,0.0
3,NaN,False,NaN,False,Atlanta,NaN,00:29:40,NaN,NaN,False,...,Variable,4.6,30324,NaN,0.0,0.0,0.0,0.0,0.0,0.0
4,NaN,False,NaN,False,Atlanta,NaN,00:29:20,NaN,NaN,False,...,Variable,4.6,30342,NaN,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207194,NaN,False,NaN,False,Miami,NaN,06:00:00,NaN,NaN,False,...,South,11.5,33183,Monday,1.0,18962.0,0.0,0.0,0.0,0.0
207195,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,Sunday,1.0,39455.0,0.0,0.0,0.0,0.0
207196,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,Saturday,1.0,37862.0,0.0,0.0,0.0,0.0
207197,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,Saturday,1.0,12981.0,0.0,0.0,0.0,0.0
207198,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,NaN,NaN,NaN,Sunday,0.0,0.0,1.0,18088.0,0.0,0.0

In [19]:
#Create consolidated lat, lng fields
USAgg['Lat']=USAgg['Start_Lat']
USAgg['Lng']=USAgg['Start_Lng']
USAgg.loc[USAgg['Lat']=='NaN', ['Lat']] = USAgg['End_Lat']
USAgg.loc[USAgg['Lng']=='NaN', ['Lng']] = USAgg['End_Lng']
USAgg=pd.DataFrame(USAgg)
USAgg=USAgg.drop(columns=['Start_Lat','Start_Lng','End_Lat','End_Lng'])

C:\Users\herre\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

In [20]:
pd.options.display.max_columns=60
pd.options.display.max_rows=200
display(USAgg)

,Airport_Code,Amenity,Astronomical_Twilight,Bump,City,Civil_Twilight,CleanUpTime,Country,County,Crossing,Date,Description,Distance(mi),Give_Way,Humidity(%),ID,Junction,Nautical_Twilight,No_Exit,Number,Precipitation(in),Pressure(in),Railway,Roundabout,Severity,Side,Source,State,Station,Stop,Street,Sunrise_Sunset,TMC,Temperature(F),Timezone,Traffic_Calming,Traffic_Signal,Turning_Loop,Visibility(mi),Weather_Condition,Wind_Chill(F),Wind_Direction,Wind_Speed(mph),Zipcode,Day of Week,MLBGame,MLB_Attendance,NBAGame,NBA_Attendance,NFLGame,NFL_Attendance,Lat,Lng
0,NaN,False,NaN,False,Atlanta,NaN,01:15:27,NaN,NaN,False,2017-01-02,NaN,0.010,False,100.0,NaN,True,NaN,False,NaN,0.02,30.11,False,False,3.0,R,NaN,GA,False,False,NaN,Day,NaN,55.9,NaN,False,False,False,0.2,Light Rain,NaN,NNE,8.1,30354,NaN,0.0,0.0,0.0,0.0,0.0,0.0,33.652431,-84.396278
1,NaN,False,NaN,False,Atlanta,NaN,01:15:34,NaN,NaN,False,2017-01-02,NaN,0.010,False,100.0,NaN,False,NaN,False,NaN,0.02,30.11,False,False,3.0,R,NaN,GA,False,False,NaN,Day,NaN,55.9,NaN,False,False,False,0.2,Light Rain,NaN,NNE,8.1,30312,NaN,0.0,0.0,0.0,0.0,0.0,0.0,33.744976,-84.390343
2,NaN,False,NaN,False,Atlanta,NaN,00:59:34,NaN,NaN,False,2017-01-02,NaN,0.010,False,96.0,NaN,False,NaN,False,NaN,0.01,30.13,False,False,3.0,R,NaN,GA,False,False,NaN,Day,NaN,53.1,NaN,False,False,False,0.5,Light Rain,NaN,NE,6.9,30093,NaN,0.0,0.0,0.0,0.0,0.0,0.0,33.928226,-84.176018
3,NaN,False,NaN,False,Atlanta,NaN,00:29:40,NaN,NaN,False,2017-01-02,NaN,0.010,False,96.0,NaN,False,NaN,False,NaN,0.01,30.12,False,False,2.0,R,NaN,GA,False,False,NaN,Day,NaN,53.1,NaN,False,False,False,1.0,Light Rain,NaN,Variable,4.6,30324,NaN,0.0,0.0,0.0,0.0,0.0,0.0,33.821548,-84.359383
4,NaN,False,NaN,False,Atlanta,NaN,00:29:20,NaN,NaN,False,2017-01-02,NaN,0.010,False,96.0,NaN,False,NaN,False,NaN,0.01,30.12,False,False,3.0,R,NaN,GA,False,False,NaN,Day,NaN,53.1,NaN,False,False,False,1.0,Light Rain,NaN,Variable,4.6,30342,NaN,0.0,0.0,0.0,0.0,0.0,0.0,33.912338,-84.379128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207194,NaN,False,NaN,False,Miami,NaN,06:00:00,NaN,NaN,False,2017-07-31,NaN,0.709,False,87.0,NaN,False,NaN,False,NaN,NaN,29.99,False,False,2.0,R,NaN,FL,False,False,NaN,Day,NaN,78.1,NaN,False,False,False,10.0,Mostly Cloudy,NaN,South,11.5,33183,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,25.691380,-80.388950
207195,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday,1.0,39455.0,0.0,0.0,0.0,0.0,NaN,NaN
207196,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Saturday,1.0,37862.0,0.0,0.0,0.0,0.0,NaN,NaN
207197,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Saturday,1.0,12981.0,0.0,0.0,0.0,0.0,NaN,NaN
207198,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunday,0.0,0.0,1.0,18088.0,0.0,0.0,NaN,NaN

In [21]:
#Fill in null Day of Week
USAgg['Day of Week']=pd.to_datetime(USAgg['Date']).dt.day_name()

In [22]:
#Remove records with too many NA values
USAgg=USAgg.dropna(how='any',subset=['City','State','Date','Lat','Lng'])

In [23]:
display(USAgg)

,Airport_Code,Amenity,Astronomical_Twilight,Bump,City,Civil_Twilight,CleanUpTime,Country,County,Crossing,Date,Description,Distance(mi),Give_Way,Humidity(%),ID,Junction,Nautical_Twilight,No_Exit,Number,Precipitation(in),Pressure(in),Railway,Roundabout,Severity,Side,Source,State,Station,Stop,Street,Sunrise_Sunset,TMC,Temperature(F),Timezone,Traffic_Calming,Traffic_Signal,Turning_Loop,Visibility(mi),Weather_Condition,Wind_Chill(F),Wind_Direction,Wind_Speed(mph),Zipcode,Day of Week,MLBGame,MLB_Attendance,NBAGame,NBA_Attendance,NFLGame,NFL_Attendance,Lat,Lng
0,NaN,False,NaN,False,Atlanta,NaN,01:15:27,NaN,NaN,False,2017-01-02,NaN,0.010,False,100.0,NaN,True,NaN,False,NaN,0.02,30.11,False,False,3.0,R,NaN,GA,False,False,NaN,Day,NaN,55.9,NaN,False,False,False,0.2,Light Rain,NaN,NNE,8.1,30354,Monday,0.0,0.0,0.0,0.0,0.0,0.0,33.652431,-84.396278
1,NaN,False,NaN,False,Atlanta,NaN,01:15:34,NaN,NaN,False,2017-01-02,NaN,0.010,False,100.0,NaN,False,NaN,False,NaN,0.02,30.11,False,False,3.0,R,NaN,GA,False,False,NaN,Day,NaN,55.9,NaN,False,False,False,0.2,Light Rain,NaN,NNE,8.1,30312,Monday,0.0,0.0,0.0,0.0,0.0,0.0,33.744976,-84.390343
2,NaN,False,NaN,False,Atlanta,NaN,00:59:34,NaN,NaN,False,2017-01-02,NaN,0.010,False,96.0,NaN,False,NaN,False,NaN,0.01,30.13,False,False,3.0,R,NaN,GA,False,False,NaN,Day,NaN,53.1,NaN,False,False,False,0.5,Light Rain,NaN,NE,6.9,30093,Monday,0.0,0.0,0.0,0.0,0.0,0.0,33.928226,-84.176018
3,NaN,False,NaN,False,Atlanta,NaN,00:29:40,NaN,NaN,False,2017-01-02,NaN,0.010,False,96.0,NaN,False,NaN,False,NaN,0.01,30.12,False,False,2.0,R,NaN,GA,False,False,NaN,Day,NaN,53.1,NaN,False,False,False,1.0,Light Rain,NaN,Variable,4.6,30324,Monday,0.0,0.0,0.0,0.0,0.0,0.0,33.821548,-84.359383
4,NaN,False,NaN,False,Atlanta,NaN,00:29:20,NaN,NaN,False,2017-01-02,NaN,0.010,False,96.0,NaN,False,NaN,False,NaN,0.01,30.12,False,False,3.0,R,NaN,GA,False,False,NaN,Day,NaN,53.1,NaN,False,False,False,1.0,Light Rain,NaN,Variable,4.6,30342,Monday,0.0,0.0,0.0,0.0,0.0,0.0,33.912338,-84.379128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207190,NaN,False,NaN,False,Miami,NaN,06:00:00,NaN,NaN,False,2017-07-31,NaN,0.276,False,91.0,NaN,False,NaN,False,NaN,0.05,30.00,False,False,3.0,R,NaN,FL,False,False,NaN,Day,NaN,75.9,NaN,False,False,False,10.0,Light Rain,NaN,SSW,8.1,33169,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,25.927500,-80.217210
207191,NaN,False,NaN,False,Miami,NaN,06:00:00,NaN,NaN,False,2017-07-31,NaN,0.000,False,90.0,NaN,False,NaN,False,NaN,0.04,30.01,False,False,2.0,R,NaN,FL,False,False,NaN,Day,NaN,77.0,NaN,False,False,False,10.0,Light Rain,NaN,West,5.8,33169,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,25.929028,-80.206988
207192,NaN,False,NaN,False,Miami,NaN,06:00:00,NaN,NaN,False,2017-07-31,NaN,0.062,False,90.0,NaN,False,NaN,False,NaN,0.07,30.01,False,False,2.0,R,NaN,FL,False,False,NaN,Day,NaN,77.0,NaN,False,False,False,7.0,Light Rain,NaN,West,5.8,33136,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,25.788244,-80.208609
207193,NaN,False,NaN,False,Miami,NaN,06:00:00,NaN,NaN,False,2017-07-31,NaN,0.310,False,84.0,NaN,False,NaN,False,NaN,0.00,30.00,False,False,2.0,R,NaN,FL,False,False,NaN,Day,NaN,79.0,NaN,False,False,False,10.0,Overcast,NaN,SSE,8.1,33142,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,25.812520,-80.219030
207194,NaN,False,NaN,False,Miami,NaN,06:00:00,NaN,NaN,False,2017-07-31,NaN,0.709,False,87.0,NaN,False,NaN,False,NaN,NaN,29.99,False,False,2.0,R,NaN,FL,False,False,NaN,Day,NaN,78.1,NaN,False,False,False,10.0,Mostly Cloudy,NaN,South,11.5,33183,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,25.691380,-80.388950

In [24]:
#Create Day/Night, remove redundant
USAgg=USAgg.rename(columns={'Sunrise_Sunset':'Day_or_Night','Day of Week':'Day_of_Week'})
#USAgg=USAgg.drop(columns=['Astronomical_Twilight','Civil_Twilight','Nautical_Twilight'])

In [25]:
display(USAgg.columns)

Index(['Airport_Code', 'Amenity', 'Astronomical_Twilight', 'Bump', 'City',
       'Civil_Twilight', 'CleanUpTime', 'Country', 'County', 'Crossing',
       'Date', 'Description', 'Distance(mi)', 'Give_Way', 'Humidity(%)', 'ID',
       'Junction', 'Nautical_Twilight', 'No_Exit', 'Number',
       'Precipitation(in)', 'Pressure(in)', 'Railway', 'Roundabout',
       'Severity', 'Side', 'Source', 'State', 'Station', 'Stop', 'Street',
       'Day_or_Night', 'TMC', 'Temperature(F)', 'Timezone', 'Traffic_Calming',
       'Traffic_Signal', 'Turning_Loop', 'Visibility(mi)', 'Weather_Condition',
       'Wind_Chill(F)', 'Wind_Direction', 'Wind_Speed(mph)', 'Zipcode',
       'Day_of_Week', 'MLBGame', 'MLB_Attendance', 'NBAGame', 'NBA_Attendance',
       'NFLGame', 'NFL_Attendance', 'Lat', 'Lng'],
      dtype='object')

In [26]:
USAgg=USAgg[['Date','City', 'State', 'Zipcode', 'Lat', 'Lng','Day_of_Week',
       'MLBGame', 'MLB_Attendance', 'NBAGame', 'NBA_Attendance', 'NFLGame',
       'NFL_Attendance', 'CleanUpTime', 'Distance(mi)','Crossing','Amenity', 'Bump', 
        'Give_Way', 'Humidity(%)', 'Junction', 'No_Exit',
       'Number', 'Precipitation(in)', 'Pressure(in)', 'Railway', 'Roundabout',
       'Severity', 'Side', 'Station', 'Stop', 'Day_or_Night',
       'Temperature(F)', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Visibility(mi)', 'Weather_Condition', 'Wind_Chill(F)',
       'Wind_Direction', 'Wind_Speed(mph)' ]]

In [27]:
pd.options.display.max_columns=60
pd.options.display.max_rows=200
display(USAgg)

,Date,City,State,Zipcode,Lat,Lng,Day_of_Week,MLBGame,MLB_Attendance,NBAGame,NBA_Attendance,NFLGame,NFL_Attendance,CleanUpTime,Distance(mi),Crossing,Amenity,Bump,Give_Way,Humidity(%),Junction,No_Exit,Number,Precipitation(in),Pressure(in),Railway,Roundabout,Severity,Side,Station,Stop,Day_or_Night,Temperature(F),Traffic_Calming,Traffic_Signal,Turning_Loop,Visibility(mi),Weather_Condition,Wind_Chill(F),Wind_Direction,Wind_Speed(mph)
0,2017-01-02,Atlanta,GA,30354,33.652431,-84.396278,Monday,0.0,0.0,0.0,0.0,0.0,0.0,01:15:27,0.010,False,False,False,False,100.0,True,False,NaN,0.02,30.11,False,False,3.0,R,False,False,Day,55.9,False,False,False,0.2,Light Rain,NaN,NNE,8.1
1,2017-01-02,Atlanta,GA,30312,33.744976,-84.390343,Monday,0.0,0.0,0.0,0.0,0.0,0.0,01:15:34,0.010,False,False,False,False,100.0,False,False,NaN,0.02,30.11,False,False,3.0,R,False,False,Day,55.9,False,False,False,0.2,Light Rain,NaN,NNE,8.1
2,2017-01-02,Atlanta,GA,30093,33.928226,-84.176018,Monday,0.0,0.0,0.0,0.0,0.0,0.0,00:59:34,0.010,False,False,False,False,96.0,False,False,NaN,0.01,30.13,False,False,3.0,R,False,False,Day,53.1,False,False,False,0.5,Light Rain,NaN,NE,6.9
3,2017-01-02,Atlanta,GA,30324,33.821548,-84.359383,Monday,0.0,0.0,0.0,0.0,0.0,0.0,00:29:40,0.010,False,False,False,False,96.0,False,False,NaN,0.01,30.12,False,False,2.0,R,False,False,Day,53.1,False,False,False,1.0,Light Rain,NaN,Variable,4.6
4,2017-01-02,Atlanta,GA,30342,33.912338,-84.379128,Monday,0.0,0.0,0.0,0.0,0.0,0.0,00:29:20,0.010,False,False,False,False,96.0,False,False,NaN,0.01,30.12,False,False,3.0,R,False,False,Day,53.1,False,False,False,1.0,Light Rain,NaN,Variable,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207190,2017-07-31,Miami,FL,33169,25.927500,-80.217210,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,06:00:00,0.276,False,False,False,False,91.0,False,False,NaN,0.05,30.00,False,False,3.0,R,False,False,Day,75.9,False,False,False,10.0,Light Rain,NaN,SSW,8.1
207191,2017-07-31,Miami,FL,33169,25.929028,-80.206988,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,06:00:00,0.000,False,False,False,False,90.0,False,False,NaN,0.04,30.01,False,False,2.0,R,False,False,Day,77.0,False,False,False,10.0,Light Rain,NaN,West,5.8
207192,2017-07-31,Miami,FL,33136,25.788244,-80.208609,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,06:00:00,0.062,False,False,False,False,90.0,False,False,NaN,0.07,30.01,False,False,2.0,R,False,False,Day,77.0,False,False,False,7.0,Light Rain,NaN,West,5.8
207193,2017-07-31,Miami,FL,33142,25.812520,-80.219030,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,06:00:00,0.310,False,False,False,False,84.0,False,False,NaN,0.00,30.00,False,False,2.0,R,False,False,Day,79.0,False,False,False,10.0,Overcast,NaN,SSE,8.1
207194,2017-07-31,Miami,FL,33183,25.691380,-80.388950,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,06:00:00,0.709,False,False,False,False,87.0,False,False,NaN,NaN,29.99,False,False,2.0,R,False,False,Day,78.1,False,False,False,10.0,Mostly Cloudy,NaN,South,11.5

In [28]:
#Drop States Outside of Study
#USFinal=USAgg[USAgg['State'].isin(['GA','TX','FL'])]

#USFinal=USFinal.drop(USFinal[(USFinal.State=='GA') & (USFinal.City=='Dallas')].index)
#USFinal=USFinal.drop(USFinal[(USFinal.State=='TX') & (USFinal.City=='Atlanta')].index)
USFinal = USAgg
display(USFinal)

,Date,City,State,Zipcode,Lat,Lng,Day_of_Week,MLBGame,MLB_Attendance,NBAGame,NBA_Attendance,NFLGame,NFL_Attendance,CleanUpTime,Distance(mi),Crossing,Amenity,Bump,Give_Way,Humidity(%),Junction,No_Exit,Number,Precipitation(in),Pressure(in),Railway,Roundabout,Severity,Side,Station,Stop,Day_or_Night,Temperature(F),Traffic_Calming,Traffic_Signal,Turning_Loop,Visibility(mi),Weather_Condition,Wind_Chill(F),Wind_Direction,Wind_Speed(mph)
0,2017-01-02,Atlanta,GA,30354,33.652431,-84.396278,Monday,0.0,0.0,0.0,0.0,0.0,0.0,01:15:27,0.010,False,False,False,False,100.0,True,False,NaN,0.02,30.11,False,False,3.0,R,False,False,Day,55.9,False,False,False,0.2,Light Rain,NaN,NNE,8.1
1,2017-01-02,Atlanta,GA,30312,33.744976,-84.390343,Monday,0.0,0.0,0.0,0.0,0.0,0.0,01:15:34,0.010,False,False,False,False,100.0,False,False,NaN,0.02,30.11,False,False,3.0,R,False,False,Day,55.9,False,False,False,0.2,Light Rain,NaN,NNE,8.1
2,2017-01-02,Atlanta,GA,30093,33.928226,-84.176018,Monday,0.0,0.0,0.0,0.0,0.0,0.0,00:59:34,0.010,False,False,False,False,96.0,False,False,NaN,0.01,30.13,False,False,3.0,R,False,False,Day,53.1,False,False,False,0.5,Light Rain,NaN,NE,6.9
3,2017-01-02,Atlanta,GA,30324,33.821548,-84.359383,Monday,0.0,0.0,0.0,0.0,0.0,0.0,00:29:40,0.010,False,False,False,False,96.0,False,False,NaN,0.01,30.12,False,False,2.0,R,False,False,Day,53.1,False,False,False,1.0,Light Rain,NaN,Variable,4.6
4,2017-01-02,Atlanta,GA,30342,33.912338,-84.379128,Monday,0.0,0.0,0.0,0.0,0.0,0.0,00:29:20,0.010,False,False,False,False,96.0,False,False,NaN,0.01,30.12,False,False,3.0,R,False,False,Day,53.1,False,False,False,1.0,Light Rain,NaN,Variable,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207190,2017-07-31,Miami,FL,33169,25.927500,-80.217210,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,06:00:00,0.276,False,False,False,False,91.0,False,False,NaN,0.05,30.00,False,False,3.0,R,False,False,Day,75.9,False,False,False,10.0,Light Rain,NaN,SSW,8.1
207191,2017-07-31,Miami,FL,33169,25.929028,-80.206988,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,06:00:00,0.000,False,False,False,False,90.0,False,False,NaN,0.04,30.01,False,False,2.0,R,False,False,Day,77.0,False,False,False,10.0,Light Rain,NaN,West,5.8
207192,2017-07-31,Miami,FL,33136,25.788244,-80.208609,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,06:00:00,0.062,False,False,False,False,90.0,False,False,NaN,0.07,30.01,False,False,2.0,R,False,False,Day,77.0,False,False,False,7.0,Light Rain,NaN,West,5.8
207193,2017-07-31,Miami,FL,33142,25.812520,-80.219030,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,06:00:00,0.310,False,False,False,False,84.0,False,False,NaN,0.00,30.00,False,False,2.0,R,False,False,Day,79.0,False,False,False,10.0,Overcast,NaN,SSE,8.1
207194,2017-07-31,Miami,FL,33183,25.691380,-80.388950,Monday,1.0,18962.0,0.0,0.0,0.0,0.0,06:00:00,0.709,False,False,False,False,87.0,False,False,NaN,NaN,29.99,False,False,2.0,R,False,False,Day,78.1,False,False,False,10.0,Mostly Cloudy,NaN,South,11.5

In [32]:
USFinal[:50000].to_csv('USFinal_1.csv', index=False)
USFinal[50000:100000].to_csv('USFinal_2.csv', index=False)
USFinal[100000:150000].to_csv('USFinal_3.csv', index=False)
USFinal[150000:].to_csv('USFinal_4.csv', index=False)